### ISSUE TITLE
How to download Spotify list with more than 100 songs?

### ISSUE THREAD

**Issue by wrybread** [AllToMP3/alltomp3#10]
I'm trying to download a Spotify playlist that has 144 songs, but it stops at 100. Is there some way to remove that limit?

Let me know if you need a playlist to test with.

And nice work on this program!

**Comment by Sergeypt423** [comment]
Hi wrybread.
I have one question.
Have you downloaded the mp3 files or simply only the list of songs?

I'm waiting for your response.

**Comment by wrybread** [comment]
I'm trying to download the MP3s. It shows the playlist as 100 songs long. I encountered another issue: it always freezes on song #8, so I don't know if it gets a list of the next 100 songs after finishing the fire 100. 

Sorry to hit you with 2 issues at once, but any idea how to troubleshoot it freezing on song 8? It's consistent, happens on multiple computers when trying to download this playlist. I haven't tried it with a different playlist yet but I will when back at a computer.

**Comment by NTag** [comment]
Those two issues should be fixed with `alltomp3` 0.2.5 and `alltomp3-app` 0.3.3.

If you are using the application, just launch it and it will auto-update.
