### ISSUE TITLE
Unable to locate package alltomp3

### ISSUE THREAD

**Issue by Kymus** [AllToMP3/alltomp3#11]
I've been having a real battle with alltomp3 for a while now. I'll make a long story short and provide the details for the current case. I recently (today) tried to install it again and I'm getting an error "unable to locate package" at the end. 

(Ubuntu 17.10)

```
kymus@Sanxing:~$ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
Detected operating system as Ubuntu/artful.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
kymus@Sanxing:~$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree      
Reading state information... Done
E: Unable to locate package alltomp3
kymus@Sanxing:~$ cd Downloads
kymus@Sanxing:~/Downloads$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree      
Reading state information... Done
E: Unable to locate package alltomp3
kymus@Sanxing:~/Downloads$ sudo install script.deb.sh
install: missing destination file operand after 'script.deb.sh'
Try 'install --help' for more information.
kymus@Sanxing:~/Downloads$ cd
kymus@Sanxing:~$ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
Detected operating system as Ubuntu/artful.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
kymus@Sanxing:~$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree      
Reading state information... Done
E: Unable to locate package alltomp3
kymus@Sanxing:~$
```

Sorry if there is something obvious I'm not doing right; I'm still getting the hang of installation through the terminal >_<.

**Comment by NTag** [comment]
I released today a new version, for Ubuntu Artful.

Just do:
```
sudo apt-get update
sudo apt-get install alltomp3
```

**Comment by Kymus** [comment]
Thank you! Works great now!

**Comment by alazark94** [comment]
That same issue is persisting on my end

`alazar@alazar-Latitude-E5540:~$ sudo apt-get update
Hit:1 https://deb.nodesource.com/node_8.x bionic InRelease                     
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:5 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease            
Hit:6 http://et.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease        
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Ign:9 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease     
Hit:10 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release      
Hit:12 http://repo.steampowered.com/steam precise InRelease                    
Hit:13 http://et.archive.ubuntu.com/ubuntu bionic-updates InRelease            
Hit:14 http://packages.microsoft.com/repos/vscode stable InRelease             
Hit:15 http://et.archive.ubuntu.com/ubuntu bionic-backports InRelease          
Ign:16 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic InRelease       
Err:17 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release
  404  Not Found [IP: 50.97.198.58 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package alltomp3
`

**Comment by alazark94** [comment]
I'm having the same issue..
`alazar@alazar-Latitude-E5540:~$ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
[sudo] password for alazar: 
Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
alazar@alazar-Latitude-E5540:~$ sudo apt-get update
Hit:1 https://deb.nodesource.com/node_8.x bionic InRelease                     
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:5 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease            
Hit:6 http://et.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease        
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Ign:9 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease     
Hit:10 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release      
Hit:12 http://repo.steampowered.com/steam precise InRelease                    
Hit:13 http://et.archive.ubuntu.com/ubuntu bionic-updates InRelease            
Hit:14 http://packages.microsoft.com/repos/vscode stable InRelease             
Hit:15 http://et.archive.ubuntu.com/ubuntu bionic-backports InRelease          
Ign:16 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic InRelease       
Err:17 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release
  404  Not Found [IP: 50.97.198.58 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package alltomp3
`

**Comment by alazark94** [comment]
I'm having the same issue... i followed all the steps but in case i missed any please notify

`alazar@alazar-Latitude-E5540:~$ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
[sudo] password for alazar: 
Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
alazar@alazar-Latitude-E5540:~$ sudo apt-get update
Hit:1 https://deb.nodesource.com/node_8.x bionic InRelease                     
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:3 http://dl.google.com/linux/chrome/deb stable Release                     
Hit:5 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease            
Hit:6 http://et.archive.ubuntu.com/ubuntu bionic InRelease                     
Hit:7 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease        
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease              
Ign:9 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 InRelease     
Hit:10 https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 Release      
Hit:12 http://repo.steampowered.com/steam precise InRelease                    
Hit:13 http://et.archive.ubuntu.com/ubuntu bionic-updates InRelease            
Hit:14 http://packages.microsoft.com/repos/vscode stable InRelease             
Hit:15 http://et.archive.ubuntu.com/ubuntu bionic-backports InRelease          
Ign:16 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic InRelease       
Err:17 https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release
  404  Not Found [IP: 50.97.198.58 443]
Reading package lists... Done
E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
alazar@alazar-Latitude-E5540:~$ sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package alltomp3
`

**Comment by ruzito** [comment]
I have the same issue

when I try to sudo apt-get install alltomp3

it doesn't locate the package

it might have something to do with this output of apt update

```
Err:17 https://packagecloud.io/AllToMP3/alltomp3/ubuntu hirsute Release
404 Not Found [IP: 52.8.129.94 443]
```

**Comment by SephReed** [comment]
Getting this issue on EOS after a lot of wrestling (https://github.com/AllToMP3/alltomp3-app/issues/84) to get the repository set up

```
root@seph-eos:/home/seph/Downloads# os=ubuntu dist=bionic ./script.deb.sh
Detected operating system as ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
root@seph-eos:/home/seph/Downloads# apt install alltomp3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package alltomp3
```
