### ISSUE TITLE
Unable to locate package alltomp3

### ISSUE THREAD

**Issue by Reaghaar** [AllToMP3/alltomp3#12]
wagner@wagner-H14CU01 ~ $ curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
[sudo] senha para wagner: 
Sinto muito, tente novamente.
[sudo] senha para wagner: 
Detected operating system as LinuxMint/sylvia.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
wagner@wagner-H14CU01 ~ $ sudo apt-get install alltomp3[sudo] senha para wagner: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
E: Impossível encontrar o pacote alltomp3
wagner@wagner-H14CU01 ~ $

**Comment by NTag** [comment]
I released today a new version, for LinuxMint Sylvia.

Just do:
```
sudo apt-get update
sudo apt-get install alltomp3
```
