### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by karanpratapsingh** [AllToMP3/alltomp3#19]
cannot install using $ npm install git+https://github.com/AllToMP3/alltomp3

**Comment by karanpratapsingh** [comment]
@Xcess same here, let me know if you find any solution

**Comment by nicotheprogrammer** [comment]
Got similar issues on windows 10

**Comment by Delplacev** [comment]
Same problem 


```
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout prebuild
npm ERR! error: pathspec 'prebuild' did not match any file(s) known to git.
```

**Comment by nicotheprogrammer** [comment]
So anyone has a solution?

**Comment by jakopo87** [comment]
Have a look at my [fork](https://github.com/jakopo87/alltomp3.git), it worked for me after i fixed the dependencies.
Just change the url to ``npm install git+https://github.com/jakopo87/alltomp3.git``

**Comment by nicotheprogrammer** [comment]
thank you :)

**Comment by NTag** [comment]
I finally fixed this. Sorry for the delay!

`npm install alltomp3` should work.
