### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by damenor** [AllToMP3/alltomp3#6]
npm install --save alltomp3
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "alltomp3"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/alltomp3
npm ERR! 404 
npm ERR! 404  'alltomp3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/SSD2/Mis Proyectos/alltomp3/npm-debug.log
MacBook-Pro-de-Macintosh:alltomp3 dmenor$ npm install alltomp3
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "alltomp3"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/alltomp3
npm ERR! 404 
npm ERR! 404  'alltomp3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by NTag** [comment]
I am sorry, alltomp3 is not yet registered with npm, so you have to use `npm install git+https://github.com/AllToMP3/alltomp3` for now.

I updated the README.
